
development: 
  cloud_name: "dhz2ve4yb"
  api_key: "713675573791661"
  api_secret: "gXUYPHa0EOkGC-1iWL8L-l8-6IM"


production:
  cloud_name: "dhz2ve4yb"
  api_key: "713675573791661"
  api_secret: "gXUYPHa0EOkGC-1iWL8L-l8-6IM"

