default: &default
  adapter: mysql2
  encoding: utf8
  username: ninja
  password: 123
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: dev_blog

test:
  <<: *default
  database: test_blog

production:
  <<: *default
  database: production_blog