development:
  adapter: mysql2
  encoding: utf8
  username: ninja
  password: 123
  host: 127.0.0.1
  port: 3306
  database: dev_blog

test:
  adapter: mysql2
  encoding: utf8
  username: ninja
  password: 123
  host: 127.0.0.1
  port: 3306
  database: dev_blog

production:
  adapter: postgresql
  encoding: unicode
  database: blog
