development:
  adapter: postgresql
  encoding: unicode
  database: blog
  username: ninja
  password: 123

  
# test:
#   adapter: mysql2
#   encoding: utf8
#   username: ninja
#   password: 123
#   database: dev_blog

production:
  adapter: postgresql
  database: blog
  host: localhost
  encoding: utf8
  pool: 15
  password:
