development:
  adapter: postgresql
  encoding: utf8
  database: blog
  username: ninja
  password: 123

  
# test:
#   adapter: mysql2
#   encoding: utf8
#   username: ninja
#   password: 123
#   database: dev_blog

production:
  adapter: postgresql
  database: blog
  encoding: utf8
  pool: 5
  username: ninja
  password:
